# Generated by Django 5.2.1 on 2025-06-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_model',
            new_name='company',
        ),
    ]
